plugins {
    alias(libs.plugins.modDevGradle) apply false
    alias(libs.plugins.spotless)
    alias(libs.plugins.lombok) apply false
}

apply from: rootProject.file('gradle/scripts/spotless.gradle')

allprojects {
    group = mod_group_id
    version = mod_version

    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            // For Botania 1.21.1
            url = "https://maven.blamejared.com"
        }
        maven {
            name = "Curios"
            url = uri("https://maven.theillusivec4.top/")
        }
        maven {
            url = "https://www.cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
        maven { url 'https://modmaven.dev/' }
    }
}
