plugins {
    id 'net.neoforged.moddev' version '2.0.140' apply false
    id 'com.diffplug.spotless' version '8.1.0' apply false
    id 'io.freefair.lombok' version '8.14' apply false
}

allprojects {
    group = mod_group_id
    version = mod_version

    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            // For Botania 1.21.1
            url = "https://maven.blamejared.com"
        }
        maven {
            name = "Curios"
            url = uri("https://maven.theillusivec4.top/")
        }
        maven {
            url = "https://www.cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
        maven { url 'https://modmaven.dev/' }
    }
}
