org.gradle.jvmargs=-Xmx2G
org.gradle.java.installations.auto-download=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

mod_id=avaritia_integration
mod_name=AvaritiaIntegration
mod_license=MIT
mod_version=1.0
mod_group_id=committee.nova.mods
mod_authors=cnlimiter, CreepingCreeper, cu6, Frostbite-time, IAFEnvoy, MHanHanBing, Oganesson897, QiuYe, TedXenon
mod_description=NULL
