ext.ai_mod_id = 'avaritia_integration_pneumaticcraft'
ext.ai_mod_name = 'Avaritia Integration PneumaticCraft'
ext.ai_mod_description = 'Avaritia Integration module for PneumaticCraft: Repressurized.'
ext.ai_run_directory = 'integrations/pneumaticcraft'
apply from: rootProject.file('gradle/scripts/mod-project.gradle')

dependencies {
    implementation project(':core')
    implementation "curse.maven:pneumaticcraft-repressurized-281849:${pneumaticcraft_repressurized_version}"
}
