[versions]
reAvaritia = "8498772"
jei = "8811159"
refinedStorage = "8211701"
create = "7963363"
pneumaticcraftRepressurized = "8519226"
enderIo = "8192838"
appliedEnergistics = "19.2.17"
guideme = "21.1.17"
patchouli = "7730942"
curios = "6529130"
jade = "8591319"
titanium = "8760562"
industrialForegoing = "8370717"
industrialForegoingExtraUpgrades = "8428353"
botania = "456-SNAPSHOT"
mekanism = "1.21.1-10.7.19.85"
igleeLibrary = "7000755"
evolvedMekanism = "7599592"
slashbladeResharped = "2.0.7-1.21.1"
mysticalAgriculture = "8.0.28"
mysticalAgradditions = "8.0.14"
cucumber = "8.0.16"
gtceu = "7.0.2"

[libraries]
reAvaritia                  = { module = "curse.maven:re-avaritia-623969", version.ref = "reAvaritia" }
jei                         = { module = "curse.maven:jei-238222", version.ref = "jei" }
refinedStorage              = { module = "curse.maven:refined-storage-243076", version.ref = "refinedStorage" }
create                      = { module = "curse.maven:create-328085", version.ref = "create" }
pneumaticcraftRepressurized = { module = "curse.maven:pneumaticcraft-repressurized-281849", version.ref = "pneumaticcraftRepressurized" }
enderIo                     = { module = "curse.maven:ender-io-64578", version.ref = "enderIo" }
appliedEnergistics          = { module = "org.appliedenergistics:appliedenergistics2", version.ref = "appliedEnergistics" }
guideme                     = { module = "org.appliedenergistics:guideme", version.ref = "guideme" }
patchouli                   = { module = "curse.maven:patchouli-306770", version.ref = "patchouli" }
curios                      = { module = "curse.maven:curios-309927", version.ref = "curios" }
jade                        = { module = "curse.maven:jade-324717", version.ref = "jade" }
titanium                    = { module = "curse.maven:titanium-287342", version.ref = "titanium" }
industrialForegoing         = { module = "curse.maven:industrial-foregoing-266515", version.ref = "industrialForegoing" }
industrialForegoingExtraUpgrades = { module = "curse.maven:industrial-foregoing-extra-upgrades-1161049", version.ref = "industrialForegoingExtraUpgrades" }
botania                     = { module = "vazkii.botania:botania-neoforge-1.21.1", version.ref = "botania" }
mekanism                    = { module = "mekanism:Mekanism", version.ref = "mekanism" }
igleeLibrary                = { module = "curse.maven:iglee-library-541199", version.ref = "igleeLibrary" }
evolvedMekanism             = { module = "curse.maven:evolved-mekanism-1230085", version.ref = "evolvedMekanism" }
slashbladeResharped         = { module = "maven.modrinth:slashblade-resharped", version.ref = "slashbladeResharped" }
mysticalAgriculture         = { module = "maven.modrinth:mystical-agriculture", version.ref = "mysticalAgriculture" }
mysticalAgradditions        = { module = "maven.modrinth:mystical-agradditions", version.ref = "mysticalAgradditions" }
cucumber                    = { module = "maven.modrinth:cucumber", version.ref = "cucumber" }
gtceu                       = { module = "com.gregtechceu.gtceu:gtceu-1.21.1", version.ref = "gtceu" }
