ext.ai_mod_id = mod_id
ext.ai_mod_name = mod_name
ext.ai_mod_description = mod_description
ext.ai_run_directory = 'core'

apply from: rootProject.file('gradle/scripts/mod-project.gradle')

dependencies {
    // Avaritia
    implementation forge.reAvaritia
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testImplementation 'org.apache.maven:maven-artifact:3.8.5'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
}

tasks.named('test') {
    useJUnitPlatform()
}
