ext.ai_mod_id = 'avaritia_integration_ae2'
ext.ai_mod_name = 'Avaritia Integration AE2'
ext.ai_mod_description = 'Avaritia Integration module for Applied Energistics 2.'
ext.ai_run_directory = 'integrations/ae2'
apply from: rootProject.file('gradle/scripts/mod-project.gradle')

dependencies {
    implementation project(':core')
    implementation forge.appliedEnergistics
    implementation forge.guideme
}
