ext.ai_mod_id = 'avaritia_integration_ifeu'
ext.ai_mod_name = 'Avaritia Integration IFEU'
ext.ai_mod_description = 'Avaritia Integration module for Industrial Foregoing Extra Upgrades.'
ext.ai_run_directory = 'integrations/ifeu'
ext.ai_data_output_root = 'src/generated/resources/integration_packs/server_data'
ext.ai_data_existing_root = 'src/main/resources/integration_packs/server_data'
apply from: rootProject.file('gradle/scripts/mod-project.gradle')

dependencies {
    implementation forge.reAvaritia
    implementation project(':core')
    implementation forge.titanium
    implementation forge.industrialForegoing
    implementation forge.industrialForegoingExtraUpgrades
    implementation project(':integrations:industrialforegoing')
}
