ext.ai_mod_id = 'avaritia_integration_mekanism'
ext.ai_mod_name = 'Avaritia Integration Mekanism'
ext.ai_mod_description = 'Avaritia Integration module for Mekanism.'
ext.ai_run_directory = 'integrations/mekanism'
apply from: rootProject.file('gradle/scripts/mod-project.gradle')

dependencies {
    implementation forge.reAvaritia
    implementation project(':core')
    implementation forge.mekanism
    runtimeOnly variantOf(forge.mekanism) { classifier('additions') }
    runtimeOnly variantOf(forge.mekanism) { classifier('tools') }
    implementation forge.evolvedMekanism
}
