ext.ai_mod_id = 'avaritia_integration_industrialforegoing'
ext.ai_mod_name = 'Avaritia Integration Industrial Foregoing'
ext.ai_mod_description = 'Avaritia Integration module for Industrial Foregoing.'
ext.ai_run_directory = 'integrations/industrialforegoing'
apply from: rootProject.file('gradle/scripts/mod-project.gradle')

dependencies {
    implementation forge.reAvaritia
    implementation project(':core')
    implementation forge.titanium
    implementation forge.industrialForegoing
}
